### ISSUE TITLE
Structure of DukeMTMC-VideoReID

### ISSUE THREAD

**Issue by MerceaOtniel** [aimagelab/VKD#10]
Hello!

I would like to transform a dataset after the DukeMTMC-VideoReID structure used in this project and to just plug it in. However, it seems that the structure of Duke used in this project is not the same as https://github.com/Yu-Wu/DukeMTMC-VideoReID. Could you provide more details on how you structured the Duke dataset before giving it to the network?

Thank you!

**Comment by lucabergamini** [comment]
Hey @MerceaOtniel 

The DukeMTMC-VideoReID is structured as follows:

split (either train, gallery or query)
-> person folder (e.g. 7140)
----> acquisition number (e.g. 2193, more than one per person)
--------> images (e.g. 7140_C2_F0044_X200413.jpg, more than one per acquisition)

You can take a look [here](https://github.com/aimagelab/VKD/blob/master/data/dukevideoreid/data_manager.py) to see how we process it. We hash based on person_id+camera to combine frames from the same sequence.

Let me know if you have further questions :)
