### ISSUE TITLE
RuntimeError: result type Long can't be cast to the desired output type Bool

### ISSUE THREAD

**Issue by Soar-Sir** [aimagelab/VKD#13]
Hi, guys：

First of all, thank you for your outstanding work, but when I was training the teacher network, I encountered such a problem.

python train_v2v.py mars --backbone resnet50 --num_train_images 8 --p 4 --k 4 --exp_name base_mars_resnet50 --first_milestone 100 --step_milestone 100

=> MARS loaded
Dataset statistics:
  -----------------------------------------
  subset   | # ids | # tracklets | # images
  -----------------------------------------
  train    |   625 |     8298 |   509914
  query    |   626 |     1980 |   114493
  gallery  |   622 |     9330 |   543216
  -----------------------------------------
  total    |  1251 |    19608 |  1167623
  -----------------------------------------
  number of images per tracklet: 2 ~ 920, average 59.5
  -----------------------------------------
EXP_NAME:  base_mars_resnet50
Traceback (most recent call last):
  File "train_v2v.py", line 125, in <module>
    main()
  File "train_v2v.py", line 96, in main
    triplet_loss_batch = triplet_loss(embeddings, y)
  File "/home/fei/code/VKD/model/loss.py", line 208, in __call__
    return super(OnlineTripletLoss, self).__call__(*args, **kwargs)
  File "/home/fei/anaconda3/envs/VKD/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fei/code/VKD/model/loss.py", line 146, in forward
    negative_mask = same_id_mask ^ 1
RuntimeError: result type Long can't be cast to the desired output type Bool

How can I fix it ？

**Comment by Soar-Sir** [comment]
Besides, can you share the "test_track.txt" in VeRi776? This file was not included in their original dataset. Thanks a lot!

**Comment by angpo** [comment]
Hi, 

The error is probably due to the new version of Pytorch; however, you can fix it by replacing the "1" with "True" (as suggested [here](https://github.com/jackie840129/STE-NVAN/issues/17)).  

Regarding VeRi776, you can download from [here](https://github.com/lxc86739795/vehiclereid_baseline/blob/master/list/veri_test_track_list.txt) the file you are looking for.
