### ISSUE TITLE
Heatmap code?

### ISSUE THREAD

**Issue by donghaiwang** [aimagelab/VKD#2]
Can you upload the code that draws the heatmap in your paper, thanks.

**Comment by angpo** [comment]
Hi, 

We have just uploaded the [code](https://github.com/aimagelab/VKD/blob/master/tools/save_heatmaps.py) for drawing the heatmaps. Please note that the script has been conceived for comparing the heatmaps of two distinct networks (in our experiments, the teacher and the student one). Therefore, you can run it with the following command:

`python ./tools/save_heatmaps.py mars <path-to-teacher-net> --chk_net1 <teacher-checkpoint-name> <path-to-student-net> --chk_net2 <student-checkpoint-name> --dest_path <output-dir>`

Regards, 
A.
