### ISSUE TITLE
Animal Re-ID Details

### ISSUE THREAD

**Issue by 07Agarg** [aimagelab/VKD#22]
Hi Authors, Thanks for the nice work and sharing the GitHub code!

I am trying to reproduce the results of Table 7 for Amur Tiger for animal re-identification task. The command.txt of the released code has commands for Image To Video and Video To Video settings. It can be a great help to let me know how to use the GitHub repository for the Image 2 Image setting. 

Also, in the tools/ subdirectory, there are two training files, train_v2v.py, and train_distill.py. Which of these two files should I use for the Image2Image setting? If possible, please let me know the details of the hyperparameter used for the same. 

Thanks again!

**Comment by angpo** [comment]
Hi, 

To reproduce the results on ATRW, you have to train the teacher at first (hence, train_v2v.py), and then the student (train_distill.py). You can use these scripts even for the I2I setting. 

I will send you an email to share the hyperparameters.

Best regards,
A

**Comment by 07Agarg** [comment]
Hi, Thanks for your quick response. 

Isn't the code not integrated for Amur Tigers Dataset? 
In Line 89, data/datasets.py, the ``Datasets`` dictionary listed does not include Amur Tigers. Similarly, in Line 59, data/misc.py, ``get_transforms`` function is not customized for Amur Tigers dataset. 

Thanks,

**Comment by angpo** [comment]
Yes, the public repo does not support the Amur Tigers dataset. 
However, I will try to help you by e-mail. 

Thanks,
