### ISSUE TITLE
Error on training: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by Perry0rnitorincul** [aimagelab/VKD#23]
Hello,
I am trying to reproduce the results on Google Collab. I followed the instructions, but maybe I have mistaken something:
I have all the needed files on a Google Drive and, therefore, the datasets structure looks like this: VKD-master/datasets/mars and there are 3 folders (info, bbox_train, bbox_test). 
However,  when I start running the training command, I get the following error:
"RuntimeError: stack expects a non-empty TensorList"
I have attached a file of the entire log. Also, when I tried on the pre-trained model, the same error occurred. 
Any change I do, brings me back to this same error. Please, guide me towards a solution. Any idea is welcomed.
Thank you,
Anca
![error_lic](https://user-images.githubusercontent.com/72354889/172073635-160865c4-812b-4fc8-81b5-f514c96af768.PNG)
![path_lic](https://user-images.githubusercontent.com/72354889/172073637-a5f970e4-2f0d-483d-977a-37706892a80a.PNG)

**Comment by angpo** [comment]
I guess that it's a problem due to wrong paths. The code assumes that the datasets' tree is placed in the current working directory. Therefore, please check if VKD-master is being set as your current working directory within the notebook environment.

**Comment by Perry0rnitorincul** [comment]
I have configured the absolute path in the colab notebook enviroment. Also, to be sure, I have added the path in every .py file (attached a photo). Still, when hitting the train command I get the same error. This is the link from the notebook env.:
https://colab.research.google.com/drive/1sPZJIyUXNiFfzdzSkgltY4OvrgE7BOY-?usp=sharing
I have added there a "tree" command so you can visualize how the project structure looks like, but I skipped the bbox_train/bbox_test directories because of their large files. However, the folders are where specified, under the /datasets/mars directory. Could you please have a look? Maybe you notice something. I really do not know what else to change.
Many Thanks!
![image](https://user-images.githubusercontent.com/72354889/172262691-6dd56095-6076-4b1f-a087-4b87b24e69b6.png)

**Comment by Perry0rnitorincul** [comment]
Thank you for checking my code. I do really appreciate it! Unfortunately, I tried with your suggestion and I am still having the same error. I tried with the previous version of code (original code) and printed the conf.nas_path and it is: /content/drive/My Drive/Licenta/VKD/datasets (attached photo).
I also took the installations again one by one with all the prerequisites (I think in the beginning I was not having the right version of conda). Do you know, what else could be checked...?
Thank you, again! 
![image](https://user-images.githubusercontent.com/72354889/172724539-873d6116-07fc-4325-80f3-5dcdcce6c1fa.png)

**Comment by angpo** [comment]
Ok, please email me at angelo.porrello@unimore.it and let's solve the issue together.
