### ISSUE TITLE
inputs

### ISSUE THREAD

**Issue by weilli** [aimagelab/VKD#3]
I'm sorry I have little knownledge about video reid.
What form is the input？Is it a sequential input？

**Comment by angpo** [comment]
Hi, 

The shape of the input is (B,T,C,H,W), where:
- B equals the batch size (as mentioned in Section 4.1 of our paper, each batch contains 8 identities with 4 samples each; hence B=8*4=32)
- T equals the number of frames sampled from each video (during the first training step, each of the B=32 sample comprises T=8 images equally spaced in a tracklet)
- (H,W) is the resolution of each RGB image (hence, C=3)

A.
