### ISSUE TITLE
How many GPUs are used for training?

### ISSUE THREAD

**Issue by wangpichao** [aimagelab/VKD#4]
How many GPUs are used for training? I used 8 gpus, and the results are not good.

**Comment by angpo** [comment]
Hi, 

We have used two GPUs for training the teacher, and just one for the student. 
Let me know if this solves the problems you are dealing with.

A.

**Comment by wangpichao** [comment]
I tried to using two GPUs, but came across the following error and got struck:
CUDA_VISIBLE_DEVICES=0,1 python ./tools/train_v2v.py mars --backbone resnet50 --num_train_images 8 --p 8 --k 4 --exp_name base_mars_resnet50 --first_milestone 100 --step_milestone 100
=> MARS loaded
Dataset statistics:
  -----------------------------------------
  subset   | # ids | # tracklets | # images
  -----------------------------------------
  train    |   625 |     8298 |   509914
  query    |   626 |     1980 |   114493
  gallery  |   622 |     9330 |   543216
  -----------------------------------------
  total    |  1251 |    19608 |  1167623
  -----------------------------------------
  number of images per tracklet: 2 ~ 920, average 59.5
  -----------------------------------------
EXP_NAME:  base_mars_resnet50
Epoch: 0 - triplet 1.54 - class 6.44
Epoch: 5 - triplet 0.34 - class 4.44
Epoch: 10 - triplet 0.16 - class 2.76
Epoch: 15 - triplet 0.12 - class 1.69
Epoch: 20 - triplet 0.08 - class 1.07
Epoch: 25 - triplet 0.04 - class 0.64
Epoch: 30 - triplet 0.04 - class 0.50
Epoch: 35 - triplet 0.03 - class 0.33
^[[A^[[A^[[AEpoch: 40 - triplet 0.02 - class 0.25
Epoch: 45 - triplet 0.03 - class 0.21
I2V
top1:78.18% top5:89.19% top10:91.97% mAP:67.63%
V2V
top1:85.56% top5:94.14% top10:96.16% mAP:75.78%
Traceback (most recent call last):
  File "./tools/train_v2v.py", line 125, in <module>
    main()
  File "./tools/train_v2v.py", line 84, in main
    saver.save_net(net.module, f'chk_{e // args.save_epoch_interval}')
  File "/home/pichao.wang/code/VKD/utils/saver.py", line 78, in save_net
    raise ValueError('PREVENT OVERWRITE WEIGHTS')
ValueError: PREVENT OVERWRITE WEIGHTS

**Comment by wangpichao** [comment]
I will delete the logs and try again.

**Comment by wangpichao** [comment]
Thanks. And two GPUs working for teacher network. And the results are:
I2V
top1:81.67% top5:92.12% top10:93.64% mAP:73.68%
V2V
top1:88.28% top5:96.31% top10:97.12% mAP:81.05%

**Comment by angpo** [comment]
Oh, good, the results you have achieved are comparable with the ones discussed in our paper.
