### ISSUE TITLE
How to conduct cross-architecture transfer?

### ISSUE THREAD

**Issue by LiangHann** [aimagelab/VKD#9]
How to conduct cross-architecture transfer? What is the command? or what codes need I revise? Thanks.

**Comment by angpo** [comment]
The code is the same as for self-distillation (just provide a value for the parameter `—student` being different from the previous one):

`python ./tools/train_distill.py mars ./logs/base_mars_resnet101 --student ./logs/base_mars_resnet34 --exp_name distill_mars_resnet101_to_resnet34 --p 12 --k 4 --step_milestone 150 --num_epochs 500 `
